import '@fontsource/roboto/300.css';
import '@fontsource/roboto/400.css';
import '@fontsource/roboto/500.css';
import '@fontsource/roboto/700.css';
import './globals.css';
import { AuthProvider } from "@/app/components/provider/auth_provider";
import { UserProfileImageProvider } from "@/app/components/provider/user_profile_image";
import Head from "next/head";
import Script from "next/script";

export const metadata = {
    title: 'MusicSNS',
    description: 'Generated by create next app',
    name: "viewport",
    content: "initial-scale=1, width=device-width",

};

export default function RootLayout({ children }) {
    return (
        <html lang="en">
                <body>
                    {children}
                </body>
        </html>
    );
}