import { Inter } from 'next/font/google'
import './globals.css'
import {AuthProvider} from "@/app/provider/auth_provider";
import {UserProfileImageProvider} from "@/app/provider/user_profile_image";

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
      <AuthProvider>
          <UserProfileImageProvider>
              {children}
          </UserProfileImageProvider>
      </AuthProvider>
      </body>
    </html>
  )
}
